---
title: "Edx Movie Lens, Harvard 125.9"
author: "Doug Northcott"
date: "6/13/2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Movie Lens

This project is to analyze this large data sets that is beyond the limit of most machines and subject this dataset to machine learning to find the most accurate predicting model.

```{r, echo=FALSE}
###################################
# Create edx set and validation set
###################################

# Note: this process could take a couple of minutes

if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
if(!require(caret)) install.packages("caret", repos = "http://cran.us.r-project.org")

# MovieLens 10M dataset:
# https://grouplens.org/datasets/movielens/10m/
# http://files.grouplens.org/datasets/movielens/ml-10m.zip

dl <- tempfile()
download.file("http://files.grouplens.org/datasets/movielens/ml-10m.zip", dl)

ratings <- read.table(text = gsub("::", "\t", readLines(unzip(dl, "ml-10M100K/ratings.dat"))),
                      col.names = c("userId", "movieId", "rating", "timestamp"))

movies <- str_split_fixed(readLines(unzip(dl, "ml-10M100K/movies.dat")), "\\::", 3)
colnames(movies) <- c("movieId", "title", "genres")
movies <- as.data.frame(movies) %>% mutate(movieId = as.numeric(levels(movieId))[movieId],
                                           title = as.character(title),
                                           genres = as.character(genres))

movielens <- left_join(ratings, movies, by = "movieId")

# Validation set will be 10% of MovieLens data

set.seed(1) # if using R 3.6.0: set.seed(1, sample.kind = "Rounding")
test_index <- createDataPartition(y = movielens$rating, times = 1, p = 0.1, list = FALSE)
edx <- movielens[-test_index,]
temp <- movielens[test_index,]

# Make sure userId and movieId in validation set are also in edx set

validation <- temp %>% 
     semi_join(edx, by = "movieId") %>%
     semi_join(edx, by = "userId")

# Add rows removed from validation set back into edx set

removed <- anti_join(temp, validation)
edx <- rbind(edx, removed)

rm(dl, ratings, movies, test_index, temp, movielens, removed)
```

## Basic Stats


```{r}
summary(edx)
library(psych)
library(magrittr)
library(tidyverse)
describe(edx)
edxg <- edx %>% separate_rows(genres, sep = "\\|")
edxg %>%
	group_by(genres) %>%
	summarize(count = n()) %>%
	arrange(desc(count))
```
```{r}
edxg[edxg$genres == "Drama", "genres"] <- 1
edxg[edxg$genres == "Comedy", "genres"] <- 2
edxg[edxg$genres == "Action", "genres"] <- 3
edxg[edxg$genres == "Thriller", "genres"] <- 4
edxg[edxg$genres == "Adventure", "genres"] <- 5
edxg[edxg$genres == "Romance", "genres"] <- 6
edxg[edxg$genres == "Sci-Fi", "genres"] <- 7
edxg[edxg$genres == "Crime", "genres"] <- 8
edxg[edxg$genres == "Fantasy", "genres"] <- 9
edxg[edxg$genres == "Children", "genres"] <- 10
edxg[edxg$genres == "Horror", "genres"] <- 11
edxg[edxg$genres == "Mystery", "genres"] <- 12
edxg[edxg$genres == "War", "genres"] <- 13
edxg[edxg$genres == "Animation", "genres"] <- 14
edxg[edxg$genres == "Musical", "genres"] <- 15
edxg[edxg$genres == "Western", "genres"] <- 16
edxg[edxg$genres == "Film-Noir", "genres"] <- 17
edxg[edxg$genres == "Documentary", "genres"] <- 18
edxg[edxg$genres == "IMAX", "genres"] <- 19
edxg[edxg$genres == "(no genres listed)", "genres"] <- 20
head(edxg)
edxg$genres <- as.double(edxg$genres)
write.csv(edxg, "C:\\Users\\dougl\\OneDrive\\Email attachments\\Documents\\edxg.csv", row.names = FALSE)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
library(sparklyr)
library(dplyr)
spark_install()
sc <- spark_connect(master = "local")
```


```{r}
edxgspark <- spark_read_csv(sc, name = "edxg", path = "C:\\Users\\dougl\\OneDrive\\Email attachments\\Documents\\edxg.csv")
count(edxgspark)
```

```{r}
modellr <- edxgspark %>% ml_linear_regression(rating ~ genres + userId)
summary(modellr)
```


```{r}
modelglm <- edxgspark %>% ml_generalized_linear_regression(rating ~ genres + userId)
summary(modelglm)
```

```{r}
modelrf <- edxgspark %>% ml_random_forest(rating ~ genres, type = "regression")
summary(modelrf)
print(modelrf)
```

```{r}
modelgb <- edxgspark %>% ml_gradient_boosted_trees(rating ~ genres, type = "regression")
summary(modelgb)
```


```{r}
vg <- validation %>% separate_rows(genres, sep = "\\|")
vg[vg$genres == "Drama", "genres"] <- 1
vg[vg$genres == "Comedy", "genres"] <- 2
vg[vg$genres == "Action", "genres"] <- 3
vg[vg$genres == "Thriller", "genres"] <- 4
vg[vg$genres == "Adventure", "genres"] <- 5
vg[vg$genres == "Romance", "genres"] <- 6
vg[vg$genres == "Sci-Fi", "genres"] <- 7
vg[vg$genres == "Crime", "genres"] <- 8
vg[vg$genres == "Fantasy", "genres"] <- 9
vg[vg$genres == "Children", "genres"] <- 10
vg[edxg$genres == "Horror", "genres"] <- 11
vg[vg$genres == "Mystery", "genres"] <- 12
vg[vg$genres == "War", "genres"] <- 13
vg[vg$genres == "Animation", "genres"] <- 14
vg[vg$genres == "Musical", "genres"] <- 15
vg[vg$genres == "Western", "genres"] <- 16
vg[vg$genres == "Film-Noir", "genres"] <- 17
vg[vg$genres == "Documentary", "genres"] <- 18
vg[vg$genres == "IMAX", "genres"] <- 19
vg[vg$genres == "(no genres listed)", "genres"] <- 20

```

```{r}
predrf <- (modelrf,vg)
ml_regression_evaluator(predrf, label_col = "rating")
```


```{r}
predgb <- (modelgb,vg)
ml_regression_evaluator(predgb, label_col = "rating")
```

